### YamlMime:ManagedReference
items:
- uid: TirUtilities.Automation
  commentId: N:TirUtilities.Automation
  id: TirUtilities.Automation
  children:
  - TirUtilities.Automation.AutoRotate
  - TirUtilities.Automation.AutoRotate.Axis
  langs:
  - csharp
  - vb
  name: TirUtilities.Automation
  nameWithType: TirUtilities.Automation
  fullName: TirUtilities.Automation
  type: Namespace
  assemblies:
  - cs.temp.dll
references:
- uid: TirUtilities.Automation.AutoRotate
  commentId: T:TirUtilities.Automation.AutoRotate
  name: AutoRotate
  nameWithType: AutoRotate
  fullName: TirUtilities.Automation.AutoRotate
- uid: TirUtilities.Automation.AutoRotate.Axis
  commentId: T:TirUtilities.Automation.AutoRotate.Axis
  parent: TirUtilities.Automation
  name: AutoRotate.Axis
  nameWithType: AutoRotate.Axis
  fullName: TirUtilities.Automation.AutoRotate.Axis
- uid: TirUtilities.Automation
  commentId: N:TirUtilities.Automation
  name: TirUtilities.Automation
  nameWithType: TirUtilities.Automation
  fullName: TirUtilities.Automation
