### YamlMime:ManagedReference
items:
- uid: TirUtilities.Experimental.ApplicationStateMachine
  commentId: T:TirUtilities.Experimental.ApplicationStateMachine
  id: ApplicationStateMachine
  parent: TirUtilities.Experimental
  children:
  - TirUtilities.Experimental.ApplicationStateMachine.AllowPause
  - TirUtilities.Experimental.ApplicationStateMachine.BlockPause
  - TirUtilities.Experimental.ApplicationStateMachine.BlockPauseState
  - TirUtilities.Experimental.ApplicationStateMachine.CurrentState
  - TirUtilities.Experimental.ApplicationStateMachine.InGame
  - TirUtilities.Experimental.ApplicationStateMachine.QuitGame
  - TirUtilities.Experimental.ApplicationStateMachine.TogglePaused
  langs:
  - csharp
  - vb
  name: ApplicationStateMachine
  nameWithType: ApplicationStateMachine
  fullName: TirUtilities.Experimental.ApplicationStateMachine
  type: Class
  source:
    id: ApplicationStateMachine
    path: ''
    startLine: 7472
  assemblies:
  - cs.temp.dll
  namespace: TirUtilities.Experimental
  summary: "\nControls the current state of the application.\nSee also: <xref href=\"TirUtilities.Experimental.ApplicationState\" data-throw-if-not-resolved=\"false\"></xref>\n"
  example: []
  syntax:
    content: 'public class ApplicationStateMachine : StateMachine'
    content.vb: >-
      Public Class ApplicationStateMachine
          Inherits StateMachine
  inheritance:
  - System.Object
  - TirUtilities.StateMachine
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TirUtilities.Experimental.ApplicationStateMachine.TogglePaused
  commentId: M:TirUtilities.Experimental.ApplicationStateMachine.TogglePaused
  id: TogglePaused
  parent: TirUtilities.Experimental.ApplicationStateMachine
  langs:
  - csharp
  - vb
  name: TogglePaused()
  nameWithType: ApplicationStateMachine.TogglePaused()
  fullName: TirUtilities.Experimental.ApplicationStateMachine.TogglePaused()
  type: Method
  source:
    id: TogglePaused
    path: ''
    startLine: 7594
  assemblies:
  - cs.temp.dll
  namespace: TirUtilities.Experimental
  summary: "\nSwitches between the <xref href=\"TirUtilities.Experimental.PlayingState\" data-throw-if-not-resolved=\"false\"></xref> and <xref href=\"TirUtilities.Experimental.PausedState\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: public void TogglePaused()
    content.vb: Public Sub TogglePaused
  overload: TirUtilities.Experimental.ApplicationStateMachine.TogglePaused*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: TirUtilities.Experimental.ApplicationStateMachine.QuitGame
  commentId: M:TirUtilities.Experimental.ApplicationStateMachine.QuitGame
  id: QuitGame
  parent: TirUtilities.Experimental.ApplicationStateMachine
  langs:
  - csharp
  - vb
  name: QuitGame()
  nameWithType: ApplicationStateMachine.QuitGame()
  fullName: TirUtilities.Experimental.ApplicationStateMachine.QuitGame()
  type: Method
  source:
    id: QuitGame
    path: ''
    startLine: 7605
  assemblies:
  - cs.temp.dll
  namespace: TirUtilities.Experimental
  summary: 'Enters the <xref href="TirUtilities.Experimental.QuittingState" data-throw-if-not-resolved="false"></xref>. '
  example: []
  syntax:
    content: public void QuitGame()
    content.vb: Public Sub QuitGame
  overload: TirUtilities.Experimental.ApplicationStateMachine.QuitGame*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: TirUtilities.Experimental.ApplicationStateMachine.BlockPause
  commentId: M:TirUtilities.Experimental.ApplicationStateMachine.BlockPause
  id: BlockPause
  parent: TirUtilities.Experimental.ApplicationStateMachine
  langs:
  - csharp
  - vb
  name: BlockPause()
  nameWithType: ApplicationStateMachine.BlockPause()
  fullName: TirUtilities.Experimental.ApplicationStateMachine.BlockPause()
  type: Method
  source:
    id: BlockPause
    path: ''
    startLine: 7637
  assemblies:
  - cs.temp.dll
  namespace: TirUtilities.Experimental
  syntax:
    content: public void BlockPause()
    content.vb: Public Sub BlockPause
  overload: TirUtilities.Experimental.ApplicationStateMachine.BlockPause*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: TirUtilities.Experimental.ApplicationStateMachine.AllowPause
  commentId: M:TirUtilities.Experimental.ApplicationStateMachine.AllowPause
  id: AllowPause
  parent: TirUtilities.Experimental.ApplicationStateMachine
  langs:
  - csharp
  - vb
  name: AllowPause()
  nameWithType: ApplicationStateMachine.AllowPause()
  fullName: TirUtilities.Experimental.ApplicationStateMachine.AllowPause()
  type: Method
  source:
    id: AllowPause
    path: ''
    startLine: 7638
  assemblies:
  - cs.temp.dll
  namespace: TirUtilities.Experimental
  syntax:
    content: public void AllowPause()
    content.vb: Public Sub AllowPause
  overload: TirUtilities.Experimental.ApplicationStateMachine.AllowPause*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: TirUtilities.Experimental.ApplicationStateMachine.CurrentState
  commentId: P:TirUtilities.Experimental.ApplicationStateMachine.CurrentState
  id: CurrentState
  parent: TirUtilities.Experimental.ApplicationStateMachine
  langs:
  - csharp
  - vb
  name: CurrentState
  nameWithType: ApplicationStateMachine.CurrentState
  fullName: TirUtilities.Experimental.ApplicationStateMachine.CurrentState
  type: Property
  source:
    id: CurrentState
    path: ''
    startLine: 7644
  assemblies:
  - cs.temp.dll
  namespace: TirUtilities.Experimental
  syntax:
    content: public ApplicationState CurrentState { get; set; }
    parameters: []
    return:
      type: TirUtilities.Experimental.ApplicationState
    content.vb: Public Property CurrentState As ApplicationState
  overload: TirUtilities.Experimental.ApplicationStateMachine.CurrentState*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: TirUtilities.Experimental.ApplicationStateMachine.InGame
  commentId: P:TirUtilities.Experimental.ApplicationStateMachine.InGame
  id: InGame
  parent: TirUtilities.Experimental.ApplicationStateMachine
  langs:
  - csharp
  - vb
  name: InGame
  nameWithType: ApplicationStateMachine.InGame
  fullName: TirUtilities.Experimental.ApplicationStateMachine.InGame
  type: Property
  source:
    id: InGame
    path: ''
    startLine: 7646
  assemblies:
  - cs.temp.dll
  namespace: TirUtilities.Experimental
  syntax:
    content: public bool InGame { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property InGame As Boolean
  overload: TirUtilities.Experimental.ApplicationStateMachine.InGame*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: TirUtilities.Experimental.ApplicationStateMachine.BlockPauseState
  commentId: P:TirUtilities.Experimental.ApplicationStateMachine.BlockPauseState
  id: BlockPauseState
  parent: TirUtilities.Experimental.ApplicationStateMachine
  langs:
  - csharp
  - vb
  name: BlockPauseState
  nameWithType: ApplicationStateMachine.BlockPauseState
  fullName: TirUtilities.Experimental.ApplicationStateMachine.BlockPauseState
  type: Property
  source:
    id: BlockPauseState
    path: ''
    startLine: 7647
  assemblies:
  - cs.temp.dll
  namespace: TirUtilities.Experimental
  syntax:
    content: public bool BlockPauseState { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public ReadOnly Property BlockPauseState As Boolean
  overload: TirUtilities.Experimental.ApplicationStateMachine.BlockPauseState*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: TirUtilities.Experimental.ApplicationState
  commentId: T:TirUtilities.Experimental.ApplicationState
  parent: TirUtilities.Experimental
  name: ApplicationState
  nameWithType: ApplicationState
  fullName: TirUtilities.Experimental.ApplicationState
- uid: TirUtilities.Experimental
  commentId: N:TirUtilities.Experimental
  name: TirUtilities.Experimental
  nameWithType: TirUtilities.Experimental
  fullName: TirUtilities.Experimental
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: TirUtilities.StateMachine
  commentId: T:TirUtilities.StateMachine
  parent: TirUtilities
  name: StateMachine
  nameWithType: StateMachine
  fullName: TirUtilities.StateMachine
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: TirUtilities
  commentId: N:TirUtilities
  name: TirUtilities
  nameWithType: TirUtilities
  fullName: TirUtilities
- uid: TirUtilities.Experimental.PlayingState
  commentId: T:TirUtilities.Experimental.PlayingState
  name: PlayingState
  nameWithType: PlayingState
  fullName: TirUtilities.Experimental.PlayingState
- uid: TirUtilities.Experimental.PausedState
  commentId: T:TirUtilities.Experimental.PausedState
  name: PausedState
  nameWithType: PausedState
  fullName: TirUtilities.Experimental.PausedState
- uid: TirUtilities.Experimental.ApplicationStateMachine.TogglePaused*
  commentId: Overload:TirUtilities.Experimental.ApplicationStateMachine.TogglePaused
  name: TogglePaused
  nameWithType: ApplicationStateMachine.TogglePaused
  fullName: TirUtilities.Experimental.ApplicationStateMachine.TogglePaused
- uid: TirUtilities.Experimental.QuittingState
  commentId: T:TirUtilities.Experimental.QuittingState
  name: QuittingState
  nameWithType: QuittingState
  fullName: TirUtilities.Experimental.QuittingState
- uid: TirUtilities.Experimental.ApplicationStateMachine.QuitGame*
  commentId: Overload:TirUtilities.Experimental.ApplicationStateMachine.QuitGame
  name: QuitGame
  nameWithType: ApplicationStateMachine.QuitGame
  fullName: TirUtilities.Experimental.ApplicationStateMachine.QuitGame
- uid: TirUtilities.Experimental.ApplicationStateMachine.BlockPause*
  commentId: Overload:TirUtilities.Experimental.ApplicationStateMachine.BlockPause
  name: BlockPause
  nameWithType: ApplicationStateMachine.BlockPause
  fullName: TirUtilities.Experimental.ApplicationStateMachine.BlockPause
- uid: TirUtilities.Experimental.ApplicationStateMachine.AllowPause*
  commentId: Overload:TirUtilities.Experimental.ApplicationStateMachine.AllowPause
  name: AllowPause
  nameWithType: ApplicationStateMachine.AllowPause
  fullName: TirUtilities.Experimental.ApplicationStateMachine.AllowPause
- uid: TirUtilities.Experimental.ApplicationStateMachine.CurrentState*
  commentId: Overload:TirUtilities.Experimental.ApplicationStateMachine.CurrentState
  name: CurrentState
  nameWithType: ApplicationStateMachine.CurrentState
  fullName: TirUtilities.Experimental.ApplicationStateMachine.CurrentState
- uid: TirUtilities.Experimental.ApplicationStateMachine.InGame*
  commentId: Overload:TirUtilities.Experimental.ApplicationStateMachine.InGame
  name: InGame
  nameWithType: ApplicationStateMachine.InGame
  fullName: TirUtilities.Experimental.ApplicationStateMachine.InGame
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: TirUtilities.Experimental.ApplicationStateMachine.BlockPauseState*
  commentId: Overload:TirUtilities.Experimental.ApplicationStateMachine.BlockPauseState
  name: BlockPauseState
  nameWithType: ApplicationStateMachine.BlockPauseState
  fullName: TirUtilities.Experimental.ApplicationStateMachine.BlockPauseState
