apiRules:
- include:
    uidRegex: ^TirUtilities
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace
- exclude:
    uidRegex: ^TirUtilities.External
    type: Namespace