apiRules:
- include:
    uidRegex: ^TirUtilities
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: ^TirUtilities\.External
    type: Namespace
- exclude:
    uidRegex: ^NoDoc
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace